name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --fund=false
      - name: Build (if present)
        run: npm run build --if-present

  frontend:
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --fund=false
      - name: Build (if present)
        run: npm run build --if-present


